[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.2",
    "numpy>=2.3.5",
    "sounddevice>=0.5.3",
    "uvicorn>=0.38.0",
]
